[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiokafka>=0.13.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.136.0",
    "numpy>=2.2.6",
    "opencv-python>=4.13.0.92",
    "psutil>=7.2.2",
    "pydantic>=2.13.2",
    "pydantic-settings>=2.13.1",
    "pymilvus>=2.6.12",
    "supervision>=0.27.0.post2",
    "tenacity>=9.1.4",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "trackers>=2.3.0",
    "tritonclient[grpc]>=2.67.0",
    "ultralytics>=8.4.38",
    "uvicorn[standard]>=0.44.0",
]
